apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app-1.0
  template:
    metadata:
      labels:
        app: flask-app-1.0
    spec:
      containers:
      - name: flask-app-1.0
        image: gcr.io/hoyahacks-376115/flask-kubernetes:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app-deployment
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer