apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ingest-app-1.0
  template:
    metadata:
      labels:
        app: ingest-app-1.0
    spec:
      containers:
      - name: ingest-container-1.0
        image: gcr.io/bitcamp-2023/ingest-container:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ingest-service
spec:
  selector:
    app: ingest-deployment
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer