apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ingest-app
  template:
    metadata:
      labels:
        app: ingest-app
    spec:
      containers:
      - name: ingest-container
        image: gcr.io/bitcamp-2023/ingest-container:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        volumeMounts:
        # volumes to mount
        - name: secret-volume # matches secret name
          # path for this secret to be available at
          mountPath: "/opt/firebase"
          readOnly: true # no editing!
      volumes:
      # create volumes
      - name: secret-volume # name to match for mounting
        secret:
          secretName: firebase-secret # name of secret
---
apiVersion: v1
kind: Service
metadata:
  name: ingest-service
spec:
  selector:
    app: ingest-deployment
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer